In [1]:
 print("SEP 786 - Course Project - Maged Eid")

SEP 786 - Course Project - Maged Eid


In [2]:
import numpy as np
import pandas as pd
import csv
import time
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('C:\ALL\McMaster M.Eng. Study\SEP 786 - Artificial Intelligence and Machine Learning Fundamentals (First Term)\ObesityDataSet_raw_and_data_sinthetic.csv')

In [4]:
print(df.head())

   Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        

In [5]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(df.to_string())

      Gender        Age    Height      Weight family_history_with_overweight FAVC      FCVC       NCP        CAEC SMOKE      CH2O  SCC       FAF       TUE        CALC                 MTRANS           NObeyesdad
0     Female  21.000000  1.620000   64.000000                            yes   no  2.000000  3.000000   Sometimes    no  2.000000   no  0.000000  1.000000          no  Public_Transportation        Normal_Weight
1     Female  21.000000  1.520000   56.000000                            yes   no  3.000000  3.000000   Sometimes   yes  3.000000  yes  3.000000  0.000000   Sometimes  Public_Transportation        Normal_Weight
2       Male  23.000000  1.800000   77.000000                            yes   no  2.000000  3.000000   Sometimes    no  2.000000   no  2.000000  1.000000  Frequently  Public_Transportation        Normal_Weight
3       Male  27.000000  1.800000   87.000000                             no   no  3.000000  3.000000   Sometimes    no  2.000000   no  2.000000  0.000000  

In [6]:
# Store the ((Target)) variable separately
y = df['NObeyesdad']

# Drop the ((Target)) variable from the DataFrame
df = df.drop('NObeyesdad', axis=1)

# Convert categorical variables to numerical variables
df = pd.get_dummies(df, columns=['Gender', 'family_history_with_overweight',
                                 'FAVC', 'CAEC', 'SMOKE', 'SCC', 'CALC', 'MTRANS'])

# Concatenate the target variable back to the DataFrame
df = pd.concat([df, y], axis=1)
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df.drop('NObeyesdad', axis=1), df['NObeyesdad'], test_size=0.3, random_state=42)

# Scale the data using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#PCA #PCA #PCA #PCA #PCA #PCA #PCA #PCA #PCA #PCA

# Perform PCA and record the time taken
start_time = time.time()
pca = PCA(n_components=10)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)
pca_time = time.time() - start_time

# Train a logistic regression model on the scaled data and record the time taken
start_time = time.time()
lr = LogisticRegression(random_state=42, max_iter=1000)
lr.fit(X_train_scaled, y_train)
training_time = time.time() - start_time

# Evaluate the performance of the model on the testing set
y_pred = lr.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Get the predicted labels for the testing set
y_pred = lr.predict(X_test_scaled)

# confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print confusion matrix
print("Confusion matrix:")
print(cm)

# Print the time taken for PCA and training
print("Time taken for PCA:", pca_time)
print("Time taken for training:", training_time)


Accuracy: 0.862776025236593
Confusion matrix:
[[84  2  0  0  0  0  0]
 [11 63  0  0  0 14  5]
 [ 0  0 90  7  2  0  3]
 [ 0  0  2 86  0  0  0]
 [ 0  0  0  1 97  0  0]
 [ 0  9  0  0  0 63 16]
 [ 0  0  4  0  1 10 64]]
Time taken for PCA: 0.0666201114654541
Time taken for training: 0.09644436836242676


In [7]:
import seaborn as sns
import matplotlib.pyplot as plt

# Get the predicted labels for the testing set
y_pred = lr.predict(X_test_scaled)

# Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot the confusion matrix as a heatmap
sns.heatmap(cm, annot=True, cmap='Blues', fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion matrix')
plt.show()


In [8]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
import time

start_time = time.time()

# two dimensional space
lda = LDA(n_components=2)

# Fit the LDA model to the training data
X_train_lda = lda.fit_transform(X_train, y_train)

# Transform the testing data using the LDA model
X_test_lda = lda.transform(X_test)

end_time = time.time()
lda_time = end_time - start_time

start_time = time.time()

# Train a logistic regression model on the transformed training data
lr = LogisticRegression(solver='lbfgs', max_iter=1000)
lr.fit(X_train_lda, y_train)

end_time = time.time()
training_time = end_time - start_time

# Make predictions on the testing data using the trained model
y_pred = lr.predict(X_test_lda)

# Calculate the accuracy score and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

print("Time taken for LDA:", lda_time)
print("Time taken for training:", training_time)
print("Accuracy score:", accuracy)
print("Confusion matrix:\n", confusion)


Time taken for LDA: 0.008990287780761719
Time taken for training: 0.06676769256591797
Accuracy score: 0.9100946372239748
Confusion matrix:
 [[82  4  0  0  0  0  0]
 [10 68  0  0  0 15  0]
 [ 0  0 99  0  0  0  3]
 [ 0  0  1 87  0  0  0]
 [ 0  0  0  0 98  0  0]
 [ 0  5  0  0  0 75  8]
 [ 0  0  2  0  0  9 68]]
